<template>
 <div class="workspace-shell">
  <div v-if="mobileNav" class="nav-shade" @click="mobileNav=false"></div>
  <aside ref="sidebar" class="sidebar" :class="{'is-open':mobileNav}"><a href="#admcode" class="brand" @click.prevent="navigate('admcode')"><span class="brand-mark"><b></b><b></b><b></b><b></b></span><span>kkdugi<span class="brand-dot">.</span></span><small>ADMIN</small></a><div class="workspace-label"><span class="workspace-icon"><i class="las la-cube"></i></span><div><strong>{{t('workspace')}}</strong><small>System workspace</small></div></div><button class="icon-button sidebar-close mobile-toggle" @click="mobileNav=false" :aria-label="t('close')"><i class="las la-times"></i></button><div class="nav-heading">{{t('system')}}</div><nav :aria-label="t('system')"><button v-for="(def,key) in screenDefs" :key="key" class="nav-item" :class="{active:screen===key}" :aria-current="screen===key?'page':undefined" @click="navigate(key)"><i :class="def.icon"></i><span>{{t(key)}}</span><i v-if="screen===key" class="las la-angle-right nav-arrow"></i></button></nav><div class="sidebar-bottom"><div class="side-note"><i class="las la-shapes"></i><span>{{t('start_here')}}</span></div><div class="side-version"><span><i class="las la-sun"></i> {{t('light')}}</span><span>v0.1</span></div></div></aside>
  <div class="main-shell" :inert="mobileNav"><header class="topbar"><div class="topbar-left"><button class="icon-button mobile-toggle" @click="mobileNav=!mobileNav" :aria-label="t('menu')" :aria-expanded="mobileNav"><i class="las la-bars"></i></button><span class="topbar-section">{{t('system')}}</span><span class="breadcrumb-separator">/</span><span>{{t(screen)}}</span></div><div class="topbar-right"><div class="locale-select"><i class="las la-globe"></i><select :value="state.locale" @change="changeLocale($event.target.value)" :aria-label="t('language')"><option value="ko_KR">한국어</option><option value="en_US">English</option></select></div><span class="topbar-divider"></span><div class="operator"><span class="avatar">A</span><span>{{t('operator')}}</span></div></div></header>
   <main id="main-content" class="main-content">
    <div class="page-heading"><div><div class="eyebrow">SYSTEM MANAGEMENT <span class="eyebrow-line"></span> {{screen.toUpperCase()}}</div><h1>{{t(screen)}}</h1><p>{{t(def.desc)}}</p></div><div class="heading-icon"><i :class="def.icon"></i></div></div>
    <div v-if="config.mode==='preview'" class="preview-banner"><i class="las la-flask"></i><strong>{{t('preview')}}</strong><span>{{t('preview_note')}}</span></div>
    <div v-if="def.batch" class="batch-bar" :class="{'has-changes':dirty}"><div class="batch-status"><span class="save-indicator"><i :class="dirty?'las la-pen':'las la-check'"></i></span><div><strong>{{t(dirty?'pending':'clean')}}</strong><small v-if="dirty">{{t('new')}} {{changes.insert.length}} · {{t('changed')}} {{changes.update.length}} · {{t('removed')}} {{changes.delete.length}}</small><small v-else>{{t('batch_hint')}}</small></div></div><div class="batch-buttons"><button class="button" :disabled="!dirty||saving" @click="discard">{{t('discard')}}</button><button class="button is-primary" :disabled="!dirty||saving" @click="save"><i class="las la-check"></i>{{saving?t('saving'):t('save')}}<span v-if="dirty" class="button-counter">{{changeCount}}</span></button></div></div>
    <form class="search-panel" @submit.prevent="search"><div class="panel-heading"><span><i class="las la-filter"></i> {{t('filters')}}</span><button type="button" class="text-button filter-toggle" @click="filtersOpen=!filtersOpen" :aria-expanded="filtersOpen"><i :class="filtersOpen?'las la-angle-up':'las la-angle-down'"></i></button></div><div class="search-fields" v-show="filtersOpen"><div class="field" v-for="key in def.filters" :key="key"><label class="label" :for="'search-'+key">{{t(key)}}</label><div v-if="key==='use'||key==='status'" class="select is-fullwidth"><select :id="'search-'+key" v-model="filters[key]"><option value="">{{t('all')}}</option><option v-for="option in key==='use'?['Y','N']:statuses" :key="option" :value="option">{{key==='use'?t(option==='Y'?'enabled':'disabled'):option}}</option></select></div><input v-else class="input" :id="'search-'+key" v-model="filters[key]" :placeholder="t(key)" autocomplete="off"></div><div class="search-actions"><button type="button" class="button" @click="resetFilters"><i class="las la-undo-alt"></i>{{t('reset')}}</button><button class="button is-primary" :disabled="loading"><i class="las la-search"></i>{{t('search')}}</button></div></div><div class="collapsed-search" v-if="!filtersOpen"><span>{{Object.values(filters).filter(Boolean).join(' · ')||t('all')}}</span><button class="button is-primary" :disabled="loading">{{t('search')}}</button></div></form>
    <div v-if="error" class="error-panel page-error" role="alert"><i class="las la-exclamation-circle"></i><span>{{error}}</span><button class="text-button" @click="runLoad">{{t('retry')}}</button></div>
    <section class="list-panel" :aria-label="t(screen)+' '+t('list')" :aria-busy="loading">
     <div class="list-toolbar"><div class="list-title"><h2>{{t(screen)}} <span class="count-chip">{{total}}</span></h2><span v-if="selected.length" class="selection-count">{{selected.length}} {{t('selected')}}</span></div><div class="toolbar-actions"><button class="icon-button refresh-button" :aria-label="t('refresh')" @click="refresh" :disabled="loading"><i class="las la-sync-alt"></i></button><button v-if="screen==='aduser'" class="button" :disabled="!selected.length||!statuses.length" @click="changeStatus"><i class="las la-user-check"></i>{{t('change_status')}}</button><button v-if="def.batch" class="button danger-ghost" :disabled="!selected.length" @click="removeRows(selected)"><i class="las la-trash-alt"></i>{{t('delete')}}</button><button class="button is-primary is-light" @click="editRow()"><i class="las la-plus"></i>{{t('add')}}</button></div></div>
     <div v-if="screen==='admcode'" class="code-breadcrumb"><button @click="goLevel(-1)" class="crumb-root"><i class="las la-folder-open"></i>{{t('root')}}</button><template v-for="(crumb,index) in trail" :key="crumb.id"><i class="las la-angle-right"></i><button @click="goLevel(index)">{{localeValue(crumb,state.locale)||crumb.code}}</button></template><button class="up-button" :disabled="!trail.length" @click="goLevel(trail.length-2)"><i class="las la-level-up-alt"></i>{{t('up')}}</button></div>
     <div class="grid-zone"><Grid ref="grid" :key="screen+'-'+state.locale" :rows="visibleRows" :columns="columns" :locale="state.locale" :title="t(screen)" :loading="loading" :inline-messages="screen==='admmsge'" @selection="selected=$event" @edit="cellEdited"/><div v-if="!loading&&!visibleRows.length" class="empty-state"><i class="las la-inbox"></i><h3>{{t('empty')}}</h3><p>{{t('empty_hint')}}</p><button class="button" @click="editRow()"><i class="las la-plus"></i>{{t('add')}}</button></div></div>
     <div class="grid-footer"><span>{{t('total')}} <strong>{{total}}</strong> {{t('items')}}</span><div v-if="screen!=='admmenu'" class="pagination-controls"><label class="page-size"><select :value="pageSize" @change="setPageSize(+$event.target.value)" :aria-label="t('page_size')"><option :value="20">20 / {{t('page')}}</option><option :value="50">50 / {{t('page')}}</option><option :value="100">100 / {{t('page')}}</option><option :value="200">200 / {{t('page')}}</option></select></label><button class="icon-button" :disabled="page<=1||loading" @click="movePage(page-1)" :aria-label="t('previous')"><i class="las la-angle-left"></i></button><span class="current-page">{{page}}</span><span class="page-total">/ {{Math.max(1,pages)}}</span><button class="icon-button" :disabled="page>=pages||loading" @click="movePage(page+1)" :aria-label="t('next')"><i class="las la-angle-right"></i></button></div><span v-else class="muted">{{t('system')}}</span></div>
    </section>
    <div class="below-grid"><p><i class="las la-info-circle"></i><span class="desktop-hint">{{t(screen==='admmsge'?'message_inline_hint':'edit_hint')}}</span><span class="mobile-hint">{{t(screen==='admmsge'?'message_inline_hint':'mobile_hint')}}</span></p><span class="muted">kkdugi admin</span></div>
   </main>
  </div>
  <DialogHost/><div v-if="state.notice" class="toast" role="status"><i class="las la-check-circle"></i>{{state.notice}}</div>
 </div>
</template>
<script setup>
import {ref,computed,inject,onMounted,onBeforeUnmount,watch,nextTick} from 'vue';
import Grid from './Grid.vue';
import {MessageCellEditor} from './MessageCellEditor.mjs';
import DialogHost from './DialogHost.vue';
const s=inject('kkdugi');const {t,config,state,screenDefs,api,clone,payload,rowState,cleanRow,localeValue,isProtected,flatten,validate,assignmentDiff,statuses}=s;
const screen=ref(screenDefs[location.hash.slice(1)]?location.hash.slice(1):'admcode');const def=computed(()=>screenDefs[screen.value]);const filters=ref({}),applied=ref({}),rows=ref([]),baseline=ref([]),selected=ref([]),trail=ref([]),page=ref(1),pageSize=ref(20),pages=ref(1),total=ref(0),loading=ref(false),saving=ref(false),error=ref(''),tick=ref(0),grid=ref(null),mobileNav=ref(false),filtersOpen=ref(true);let generation=0,disposed=false;
const changes=computed(()=>{tick.value;return payload(rows.value,baseline.value);});const changeCount=computed(()=>changes.value.insert.length+changes.value.update.length+changes.value.delete.length);const dirty=computed(()=>def.value.batch&&changeCount.value>0);
const visibleRows=computed(()=>{if(screen.value!=='admmenu'||!applied.value.name)return rows.value;const q=applied.value.name.toLowerCase();const matches=rows.value.filter(r=>`${r.program} ${JSON.stringify(r.locale)}`.toLowerCase().includes(q));return rows.value.filter(r=>matches.some(m=>m.id===r.id||m.path?.startsWith(r.path+'/')));});
const sidebar=ref(null);const langs=computed(()=>s.languages);watch(mobileNav,async open=>{await nextTick();if(open)sidebar.value?.querySelector('button')?.focus();else document.querySelector('.topbar .mobile-toggle')?.focus();});
function errorText(e){return e.status!==undefined?s.errorText(e):e.message;}
async function load(){const id=++generation;loading.value=true;error.value='';selected.value=[];try{const result=await api.list(def.value.resource,{...applied.value,page:page.value,pageSize:pageSize.value,...(screen.value==='admcode'?{parentId:trail.value.at(-1)?.id||''}:{})});if(id!==generation||disposed)return;rows.value=(screen.value==='admmenu'?flatten(result):result.contents).map(r=>({...r,_key:r.id||r.code}));baseline.value=clone(rows.value);total.value=screen.value==='admmenu'?rows.value.length:result.totalItems;pages.value=screen.value==='admmenu'?1:result.totalPages;if(page.value>Math.max(1,pages.value)){page.value=Math.max(1,pages.value);return await load();}}catch(e){if(id===generation){error.value=errorText(e);throw e;}}finally{if(id===generation)loading.value=false;}}
async function runLoad(){try{await load();}catch{}}
async function guard(){grid.value?.stop();tick.value++;if(saving.value)return false;if(!dirty.value)return true;const result=await s.dialog.open({kind:'confirm',title:t('unsaved'),message:t('unsaved_hint'),submitLabel:t('save_leave'),onSubmit:async()=>{await save(true);},alternative:{label:t('discard_leave'),action:()=>{rows.value=clone(baseline.value);}}});return result.status==='submitted';}
async function navigate(key){if(key===screen.value){mobileNav.value=false;return;}if(!await guard())return;screen.value=key;filters.value={};applied.value={};trail.value=[];page.value=1;mobileNav.value=false;history.replaceState(null,'','#'+key);await runLoad();}
async function changeLocale(locale){if(!await guard())return;if(config.mode!=='preview'){const next=new URL(location.href);next.searchParams.set('lang',locale);location.assign(next.href);return;}state.locale=locale;document.documentElement.lang=locale.replace('_','-');}
async function search(){if(!await guard())return;applied.value=clone(filters.value);page.value=1;await runLoad();}
function resetFilters(){filters.value={};}
async function refresh(){if(await guard())await runLoad();}
async function movePage(value){if(await guard()){page.value=value;await runLoad();}}
async function setPageSize(value){if(await guard()){pageSize.value=value;page.value=1;await runLoad();}}
async function goLevel(index){if(!await guard())return;trail.value=trail.value.slice(0,index+1);page.value=1;filters.value={};applied.value={};await runLoad();}
async function descend(row){if(!row.id)return;if(!await guard())return;trail.value.push(clone(row));page.value=1;applied.value={};filters.value={};await runLoad();}
function badge(text,kind=''){const span=document.createElement('span');span.className='status-badge '+kind;span.textContent=text;return span;}
function actionButton(label,icon,fn,danger=false){const b=document.createElement('button');b.className='row-action'+(danger?' danger':'');b.type='button';b.setAttribute('aria-label',label);b.title=label;const i=document.createElement('i');i.className=icon;const text=document.createElement('span');text.textContent=label;b.append(i,text);b.onclick=e=>{e.stopPropagation();fn();};return b;}
const columns=computed(()=>{tick.value;const list=[];if(def.value.batch)list.push({headerName:t('status'),width:84,minWidth:84,cellRenderer:p=>{const value=rowState(p.data,baseline.value);return value?badge(t(value),value):badge('—','neutral');}});const simple=(field,title,width=150,editable=false)=>({field,headerName:t(title),width,editable:p=>editable&&!p.data._deleted});const local=(field,title,width=240)=>({headerName:t(title),width,valueGetter:p=>localeValue(p.data,state.locale,field),cellRenderer:p=>{const el=document.createElement('span');el.className=field==='name'||field==='label'?'name-cell':'muted';el.textContent=p.value||'—';if(screen.value==='admmenu')el.style.paddingLeft=Math.min(p.data._depth,4)*18+'px';return el;}});
if(screen.value==='admcode')list.push({...simple('code','code',165,true),editable:p=>!p.data.id&&!p.data._deleted,cellClass:'mono-cell'},local('name','code_name',205),local('remarks','remarks',310));
if(screen.value==='admmsge'){list.push({...simple('code','code',260),editable:p=>!p.data._deleted&&!baseline.value.some(r=>r._key===p.data._key),cellClass:'mono-cell'});for(const lang of langs.value)list.push({colId:'locale_'+lang.code,headerName:lang.label+' · '+lang.code,width:270,cellClass:'message-cell',valueGetter:p=>p.data.locale?.[lang.code]||'',valueSetter:p=>{p.data.locale??={};p.data.locale[lang.code]=p.newValue;return true;},editable:p=>!p.data._deleted,cellEditor:MessageCellEditor,cellEditorPopup:false});}
if(screen.value==='admmenu')list.push(local('label','label',270),simple('program','program',155),simple('path','path',240));
if(screen.value==='admauth')list.push({...simple('role','role',210),cellClass:'mono-cell'},simple('name','name',210),simple('type','type',110),simple('remarks','remarks',280));
if(screen.value==='aduser')list.push({...simple('username','username',175),cellClass:'mono-cell'},simple('name','name',145),simple('email','email',230),{...simple('status','status',125),cellRenderer:p=>badge(p.value,p.value==='ACTIVE'?'active':'neutral')},simple('lastLoginAt','last_login',185));
if(['admcode','admmenu','admauth'].includes(screen.value))list.push({...simple('use','use',105),cellRenderer:p=>badge(t(p.value==='Y'?'enabled':'disabled'),p.value==='Y'?'active':'neutral')});if(['admcode','admmenu'].includes(screen.value))list.push(simple('sort','sort',95,screen.value==='admcode'));
list.push({headerName:t('actions'),minWidth:screen.value==='aduser'?330:screen.value==='admauth'?300:190,width:screen.value==='aduser'?350:screen.value==='admauth'?320:screen.value==='admmenu'?260:220,cellRenderer:p=>{const el=document.createElement('div');el.className='row-actions';if(p.data._deleted){el.append(actionButton(t('restore'),'las la-undo',()=>restore(p.data)));return el;}if(screen.value!=='admmsge')el.append(actionButton(t('edit'),'las la-pen',()=>editRow(p.data)));if(screen.value==='admcode'&&p.data.id)el.append(actionButton(t('children'),'las la-folder-open',()=>descend(p.data)));if(screen.value==='admmenu')el.append(actionButton(t('add_child'),'las la-plus',()=>editRow(null,p.data)));if(screen.value==='admauth'){el.append(actionButton(t('menu'),'las la-sitemap',()=>mapAuthority(p.data,'menus')),actionButton(t('users'),'las la-users',()=>mapAuthority(p.data,'users')));}if(screen.value==='aduser'){el.append(actionButton(t('authorities'),'las la-shield-alt',()=>mapUser(p.data)),actionButton(t('reset_password'),'las la-key',()=>resetPassword(p.data)));}if(screen.value!=='admcode')el.append(actionButton(t('delete'),'las la-trash-alt',()=>removeRows([p.data]),true));return el;}});return list;});
function cellEdited(){tick.value++;rows.value=[...rows.value];}
function newRow(parent){const resource=def.value.resource;const locale=Object.fromEntries(langs.value.map(l=>[l.code,resource==='i18n'?'':{[resource==='menu'?'label':'name']:'',remarks:''}]));if(resource==='code')return {id:'',parentId:trail.value.at(-1)?.id||'',code:'',locale,use:'Y',path:trail.value.at(-1)?.path||'',level:trail.value.length,sort:0,extra1:'',extra2:'',extra3:'',extra4:'',extra5:''};if(resource==='i18n')return {code:'',locale};if(resource==='menu')return {id:'',program:'',icon:'las la-folder',locale,use:'Y',sort:0,path:parent?.path||'',level:parent?parent.level+1:0,_depth:parent?parent._depth+1:0,_parentId:parent?.id||''};if(resource==='authority')return {id:'',role:'',type:'ROLE',name:'',remarks:'',use:'Y',users:[],menus:[]};return {id:'',username:'',name:'',email:'',remarks:'',image:'',status:statuses[0]||''};}
async function editRow(row=null,parent=null){if(screen.value==='admmsge'){grid.value?.stop();const added={...newRow(),_key:crypto.randomUUID()};rows.value=[added,...rows.value];tick.value++;await nextTick();grid.value?.edit(0,'code');return;}if(parent&&!parent.id){s.notify('menu_parent_pending');return;}const resource=def.value.resource;let initial=row?clone(row):newRow(parent);try{if(row&&!def.value.batch){initial=await api.detail(resource,row.id);if(resource==='authority')initial=await authorityData(row.id,initial);}}catch(e){error.value=errorText(e);return;}const fixed=resource==='menu'&&row&&isProtected(row,rows.value);const fields=[];const add=(path,label,type='text',extra={})=>fields.push({path,label:t(label),type,...extra});
if(resource==='code'){add('code','code','text',{required:true,readonly:!!row?.id});add('use','use','select',{options:[{value:'Y',label:t('enabled')},{value:'N',label:t('disabled')}]});add('sort','sort','number');}
if(resource==='i18n')add('code','code','text',{required:true,readonly:!!row,hint:t('invalid_code'),full:true});
if(resource==='menu'){add('program','program','text',{readonly:fixed});add('icon','icon','text',{readonly:fixed});add('use','use','select',{readonly:fixed,options:['Y','N']});add('sort','sort','number',{readonly:fixed});add('path','parent','text',{readonly:true,full:true,hint:fixed?t('protected'):undefined});}
if(resource==='authority'){add('role','role','text',{required:true,readonly:!!row});add('type','type','text',{required:true});add('name','name','text',{required:true});add('use','use','select',{options:['Y','N']});add('remarks','remarks','textarea',{full:true});}
if(resource==='user'){add('username','username','text',{required:true,readonly:!!row});add('name','name','text',{required:true});add('email','email','email');add('status','status','select',{required:true,options:[...new Set([...statuses,initial.status].filter(Boolean))]});add('image','image','profile',{full:true});add('remarks','remarks','textarea',{full:true});}
const translation=resource==='i18n'?'message':resource==='code'?'name':resource==='menu'?'label':null;const rowLangs=[...langs.value];for(const code of Object.keys(initial.locale||{}))if(!rowLangs.some(l=>l.code===code))rowLangs.push({code,label:code});await s.dialog.open({kind:'form',title:t(row?'edit':'add')+' · '+t(screen.value),subtitle:row?.code||row?.username||row?.role||row?.program,batch:def.value.batch,wide:!!translation,initial,fields,extraTabs:resource==='code',translation,languages:rowLangs,validate:value=>{const err=validate(resource,value,langs.value);return err?t(err):'';},onSubmit:async value=>{if(def.value.batch){if(resource==='code'&&!row){value.path=(trail.value.at(-1)?.path||'')+'/'+value.code;}value._key=row?._key||crypto.randomUUID();if(row){const i=rows.value.findIndex(r=>r._key===row._key);rows.value.splice(i,1,value);}else rows.value.unshift(value);rows.value=[...rows.value];tick.value++;}else{await api.save(resource,cleanRow(value));s.notify('success');await runLoad();}}});}
async function removeRows(targets){if(!targets.length)return;if(screen.value==='admmenu'&&targets.some(r=>isProtected(r,rows.value))){await s.dialog.alert({title:t('notice'),message:t('protected')});return;}const names=targets.map(r=>r.code||r.username||r.name||localeValue(r,state.locale,'label')).join(', ');const ok=await s.dialog.confirm({title:t('confirm_delete'),message:names,description:t(def.value.batch&&screen.value!=='admmsge'?'cascade':'permanent'),danger:true,submitLabel:t('delete')});if(!ok)return;if(def.value.batch){const group=crypto.randomUUID();for(const row of rows.value){if(targets.some(r=>r._key===row._key||(screen.value==='admmenu'&&row.path?.startsWith(r.path+'/')))&&!row._deleted){row._deleted=true;row._deleteGroup=group;}}rows.value=rows.value.filter(r=>!(r._deleted&&!baseline.value.some(b=>b._key===r._key)));selected.value=[];grid.value?.clear();tick.value++;}else{try{for(const row of targets)await api.remove(def.value.resource,row.id);s.notify('success');await runLoad();}catch(e){error.value=errorText(e);}}}
function restore(row){const group=row._deleteGroup;for(const r of rows.value)if(group?r._deleteGroup===group:r._key===row._key){delete r._deleted;delete r._deleteGroup;}rows.value=[...rows.value];tick.value++;}
async function discard(){if(await s.dialog.confirm({title:t('discard'),message:t('discard_form')})){rows.value=clone(baseline.value);selected.value=[];tick.value++;}}
async function save(throwError=false){grid.value?.stop();tick.value++;const batch=changes.value;if(!changeCount.value)return;saving.value=true;error.value='';try{if(def.value.resource==='i18n'){const codes=rows.value.filter(r=>!r._deleted).map(r=>r.code);if(new Set(codes).size!==codes.length)throw Error(t('duplicate'));}for(const row of [...batch.insert,...batch.update]){const v=validate(def.value.resource,row,langs.value);if(v)throw Error(t(v));}await api.persist(def.value.resource,batch);baseline.value=clone(rows.value.filter(r=>!r._deleted));rows.value=clone(baseline.value);tick.value++;s.notify('success');try{await load();}catch{rows.value=[];baseline.value=[];total.value=0;error.value=t('saved_reload');}}catch(e){error.value=errorText(e);if(throwError)throw e;}finally{saving.value=false;}}
async function changeStatus(){await s.dialog.open({kind:'form',title:t('change_status'),message:selected.value.length+' '+t('selected'),initial:{status:statuses[0]},fields:[{path:'status',label:t('select_status'),type:'select',required:true,options:statuses}],onSubmit:async v=>{await api.changeStatus(selected.value.map(r=>r.id),v.status);s.notify('status_done');await runLoad();}});}
async function resetPassword(row){await s.dialog.open({kind:'confirm',title:t('reset_password'),message:t('reset_confirm'),description:row.username+' · '+row.name,onSubmit:async()=>{await api.resetPassword([row.id]);s.notify('reset_done');await runLoad();}});}
async function allPages(resource){let p=1,list=[],result;do{result=await api.list(resource,{page:p,pageSize:200});list.push(...result.contents);p++;}while(p<=result.totalPages);return list;}
async function authorityData(id,detail){const data=detail||await api.detail('authority',id);data.menus=flatten(await api.authorityMenus(id)).filter(m=>m.program?.trim()).map(m=>({id:m.id,authorities:m.authorities||{}}));const users=[];for(const user of data.users||[]){if(typeof user==='object'){users.push(user);continue;}const assigned=await api.userAuthorities(user);const match=assigned.find(a=>a.id===id);if(!match)throw Error(t('missing_dates'));users.push({id:user,applyStartDate:match.applyStartDate||'',applyEndDate:match.applyEndDate||''});}data.users=users;return data;}
async function mapAuthority(row,kind){try{const full=await authorityData(row.id);let items;if(kind==='menus'){items=flatten(await api.authorityMenus(row.id)).map(m=>({id:m.id,name:localeValue(m,state.locale,'label'),subtitle:m.program||m.path,depth:m._depth,assignable:!!m.program?.trim(),authorities:m.program?.trim()?{READ:false,WRITE:false,EXECUTE:false,...clone(m.authorities||{})}:{},selected:!!m.program?.trim()&&Object.values(m.authorities||{}).some(Boolean)}));}else{items=await Promise.all(full.users.map(async u=>{const user=await api.detail('user',u.id);return {...u,name:user.name,subtitle:user.username,selected:true};}));}await s.dialog.open({kind:'mapping',title:t(kind==='menus'?'menu':kind)+' · '+row.name,wide:true,mapping:kind,items,search:kind==='users'?async query=>(await api.authorityUsers(row.id,query)).map(u=>({...u,subtitle:u.username,selected:false,applyStartDate:'',applyEndDate:''})):null,onSubmit:async values=>{const selectedValues=values.filter(v=>v.selected);if(kind==='menus')full.menus=values.filter(v=>v.assignable).map(v=>({id:v.id,authorities:v.authorities}));else full.users=selectedValues.map(v=>({id:v.id,applyStartDate:v.applyStartDate||'',applyEndDate:v.applyEndDate||''}));await api.save('authority',cleanRow(full));s.notify('success');}});}catch(e){error.value=errorText(e);}}
async function mapUser(row){try{const before=await api.userAuthorities(row.id);const available=await allPages('authority');const merged=[...available,...before.filter(a=>!available.some(b=>b.id===a.id))];const items=merged.map(a=>{const old=before.find(b=>b.id===a.id);return {...a,...old,selected:!!old,subtitle:a.role,applyStartDate:old?.applyStartDate||'',applyEndDate:old?.applyEndDate||''};});await s.dialog.open({kind:'mapping',title:t('authorities')+' · '+row.name,wide:true,mapping:'authorities',items,onSubmit:async values=>{const normalized=values.filter(v=>v.selected).map(v=>{const {selected,subtitle,...value}=v;return value;});await api.saveUserAuthorities(row.id,assignmentDiff(before,normalized));s.notify('success');}});}catch(e){error.value=errorText(e);}}
function beforeUnload(e){if(dirty.value||state.dialogs.length){e.preventDefault();e.returnValue='';}}
function keydown(e){if(e.key==='Escape')mobileNav.value=false;if(mobileNav.value&&e.key==='Tab'){const nodes=[...sidebar.value.querySelectorAll('a,button')].filter(n=>n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
onMounted(()=>{runLoad();window.addEventListener('beforeunload',beforeUnload);window.addEventListener('keydown',keydown);});onBeforeUnmount(()=>{disposed=true;generation++;window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('keydown',keydown);});
</script>
