import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {createSfcRuntime} from '../../main/resources/static/js/runtime/sfc-loader.mjs';
const assets=path.resolve(import.meta.dirname,'../../main/resources/static');
const output=path.resolve(import.meta.dirname,'../../../target/pragma-test-output');
test('actual Spring-rendered screens compile with shared components and context path',async()=>{
 const context=vm.createContext({console,TextEncoder,TextDecoder,URL,URLSearchParams,setTimeout,clearTimeout,atob,btoa});context.window=context;context.self=context;context.globalThis=context;
 for(const file of ['vue.global.prod.js','vue3-sfc-loader.js'])vm.runInContext(await fs.readFile(path.join(assets,'vendor',file),'utf8'),context);
 let source;
 const runtime=createSfcRuntime({basePath:'/kk',origin:'http://localhost',vue:context.Vue,loader:context['vue3-sfc-loader'],api:{pragma:async()=>source},transport:async url=>new Response(await fs.readFile(path.join(assets,url.slice(4)),'utf8'))});
 assert.ok((await runtime.shell()).setup);
 let previous;
 for(const program of ['admin/code','admin/message','admin/menu','admin/authority'])for(const authority of [1,3,5,15]){
  // Generated by PragmaControllerTest: run mvn test before this test.
  source=await fs.readFile(path.join(output,`${program.replace('/','_')}-${authority}.vue`),'utf8');
  const component=await runtime.page('same-menu');assert.ok(component.setup);assert.notEqual(component,previous);previous=component;
 }
 source='<template><div/></template><script setup>import Bad from "https://example.com/private.vue";</script>';
 await assert.rejects(runtime.page('external'),/Unsupported SFC dependency/);
});
