<template>
 <dialog v-if="entry" ref="host" class="kk-dialog" :class="{'wide':entry.wide,'form-dialog':entry.kind!=='confirm'&&entry.kind!=='alert','danger-dialog':entry.danger}" @cancel.prevent="cancel" aria-labelledby="dialog-title" :aria-busy="busy">
  <header class="dialog-header"><div><div class="eyebrow">{{ t('workspace') }}</div><h2 id="dialog-title" tabindex="-1">{{ entry.title }}</h2><p v-if="entry.subtitle">{{ entry.subtitle }}</p></div><button class="icon-button" :disabled="busy" :aria-label="t('close')" @click="cancel"><i class="las la-times"></i></button></header>
  <form @submit.prevent="submit" class="dialog-form">
   <div class="dialog-content">
    <template v-if="discardStep"><div class="dialog-symbol"><i class="las la-exclamation-circle"></i></div><h3>{{t('discard_form')}}</h3><p>{{t('unsaved')}}</p></template>
    <template v-else>
     <div v-if="entry.kind==='confirm'||entry.kind==='alert'" class="confirm-body"><div class="dialog-symbol"><i :class="entry.danger?'las la-trash-alt':'las la-info-circle'"></i></div><h3>{{entry.message}}</h3><p>{{entry.description}}</p></div>
     <p v-else-if="entry.message" class="form-intro">{{entry.message}}</p>
     <div v-if="entry.fields" class="form-grid">
      <div v-for="field in entry.fields" :key="field.path" class="field" :class="{'full':field.full}"><label class="label" :for="'f-'+field.path">{{field.label}} <span v-if="field.required" class="required">*</span></label>
       <textarea v-if="field.type==='textarea'" :id="'f-'+field.path" class="textarea" :value="get(field.path)" @input="set(field.path,$event.target.value)" :required="field.required" :disabled="busy||field.readonly||entry.readonly" :maxlength="field.maxLength" rows="3"></textarea>
       <div v-else-if="field.type==='profile'" class="profile-editor"><div class="profile-preview"><img v-if="profileUrl&&!imageFailed" :src="profileUrl" :alt="t('profile_preview')" referrerpolicy="no-referrer" @error="imageFailed=true"><i v-else class="las la-user" aria-hidden="true"></i></div><div class="profile-input"><input :id="'f-'+field.path" class="input" type="url" :value="get(field.path)" @input="set(field.path,$event.target.value);imageFailed=false" :disabled="busy||entry.readonly" placeholder="https://"><p class="help" role="status">{{imageFailed?t('image_failed'):t('profile_preview')}}</p></div></div>
       <div v-else-if="field.type==='select'" class="select is-fullwidth"><select :id="'f-'+field.path" :value="get(field.path)" @change="set(field.path,$event.target.value)" :disabled="busy||field.readonly||entry.readonly" :required="field.required"><option v-for="opt in field.options" :key="opt.value??opt" :value="opt.value??opt" :disabled="opt.disabled">{{opt.label??opt}}</option></select></div>
       <input v-else :id="'f-'+field.path" class="input" :type="field.type||'text'" :value="get(field.path)" @input="set(field.path,field.type==='number'?$event.target.valueAsNumber:$event.target.value)" :readonly="field.readonly" :disabled="busy||entry.readonly" :required="field.required" :min="field.type==='number'?0:undefined" :placeholder="field.placeholder||''" :maxlength="field.maxLength" autocomplete="off">
       <p v-if="field.hint" class="help">{{field.hint}}</p>
      </div>
     </div>
     <section v-if="entry.translation" class="translation-section"><h3>{{t('translation')}} <span class="count-chip">{{entry.languages.length}}</span></h3>
      <div v-if="entry.translation!=='message'" class="editor-tabs" role="tablist" :aria-label="t('translation')"><button v-for="lang in entry.languages" :key="lang.code" :id="'lang-tab-'+lang.code" type="button" role="tab" :aria-selected="activeLanguage===lang.code" :aria-controls="'lang-panel-'+lang.code" :tabindex="activeLanguage===lang.code?0:-1" @click="activeLanguage=lang.code" @keydown="tabKey($event,entry.languages.map(l=>l.code),activeLanguage,'language')">{{lang.label}}</button></div>
      <div v-for="lang in entry.languages" :key="lang.code" v-show="entry.translation==='message'||activeLanguage===lang.code" class="translation-item" :id="'lang-panel-'+lang.code" :role="entry.translation==='message'?undefined:'tabpanel'" :aria-labelledby="entry.translation==='message'?undefined:'lang-tab-'+lang.code">
       <div v-if="entry.translation==='message'" class="language-label"><span>{{lang.label}}</span><code>{{lang.code}}</code></div>
       <textarea v-if="entry.translation==='message'" class="textarea" :aria-label="lang.label" :value="form.locale?.[lang.code]||''" @input="set('locale.'+lang.code,$event.target.value)" :disabled="busy||entry.readonly"></textarea>
       <template v-else><label :for="'l-'+lang.code" class="label">{{t(entry.translation==='label'?'label':'code_name')}}</label><input :id="'l-'+lang.code" class="input" :value="form.locale?.[lang.code]?.[entry.translation]||''" @input="set('locale.'+lang.code+'.'+entry.translation,$event.target.value)" :disabled="busy||entry.readonly"><label :for="'remarks-'+lang.code" class="label translation-remarks">{{t('remarks')}}</label><textarea :id="'remarks-'+lang.code" class="textarea" :value="form.locale?.[lang.code]?.remarks||''" @input="set('locale.'+lang.code+'.remarks',$event.target.value)" :disabled="busy||entry.readonly"></textarea></template>
      </div>
     </section>
     <section v-if="entry.extraTabs" class="translation-section"><h3>{{t('extra')}}</h3><div class="editor-tabs" role="tablist" :aria-label="t('extra')"><button v-for="n in 5" :key="n" :id="'extra-tab-'+n" type="button" role="tab" :aria-selected="activeExtra===n" :aria-controls="'extra-panel-'+n" :tabindex="activeExtra===n?0:-1" @click="activeExtra=n" @keydown="tabKey($event,[1,2,3,4,5],activeExtra,'extra')">{{t('extra')}} {{n}}</button></div><div v-for="n in 5" :key="n" v-show="activeExtra===n" :id="'extra-panel-'+n" role="tabpanel" :aria-labelledby="'extra-tab-'+n" class="extra-panel"><textarea class="textarea extra-textarea" :aria-label="t('extra')+' '+n" :value="get('extra'+n)" @input="set('extra'+n,$event.target.value)" :disabled="busy||entry.readonly"></textarea></div></section>
     <section v-if="entry.mapping" class="mapping-section"><div class="mapping-search"><label class="sr-only" for="mapping-query">{{t('search')}}</label><input id="mapping-query" class="input" v-model="query" :placeholder="t('available')" :disabled="busy" @keydown.enter.prevent="entry.search?searchCandidates():undefined"><button v-if="entry.search" type="button" class="button" @click="searchCandidates" :disabled="searching||busy">{{t('search')}}</button></div><p class="help">{{selectedItems.length}} {{t('assigned')}}</p>
      <div class="mapping-table-scroll"><table class="mapping-table" :class="{'menu-mapping':entry.mapping==='menus'}"><thead><tr><th scope="col">{{t(entry.mapping==='menus'?'menu':entry.mapping==='users'?'users':'authorities')}}</th><template v-if="entry.mapping==='menus'"><th v-for="flag in permissionFlags" :key="flag" scope="col" class="permission-cell">{{permissionLabel(flag)}}</th></template><template v-else><th scope="col">{{t('start')}}</th><th class="date-separator" aria-hidden="true"></th><th scope="col">{{t('end')}}</th></template></tr></thead><tbody>
       <tr v-for="item in visibleItems" :key="item.id"><th scope="row"><label class="mapping-label" :style="entry.mapping==='menus'?{paddingInlineStart:(item.depth||0)*20+'px'}:undefined"><input v-if="entry.mapping!=='menus'||item.assignable" type="checkbox" v-model="item.selected" :disabled="busy||entry.readonly||item.locked" @change="toggleItem(item)"><UserAvatar v-if="entry.mapping==='users'" :image="item.image"/><i v-if="entry.mapping==='menus'" :class="item.depth?'las la-level-up-alt tree-branch':'las la-folder'" aria-hidden="true"></i><span><strong>{{item.name||item.id}}</strong><small>{{entry.mapping==='menus'&&!item.assignable?t('menu_group'):item.subtitle}}</small></span></label></th>
        <template v-if="entry.mapping==='menus'"><td v-for="flag in permissionFlags" :key="flag" class="permission-cell"><input v-if="item.assignable&&Object.prototype.hasOwnProperty.call(item.authorities,flag)" type="checkbox" v-model="item.authorities[flag]" :aria-label="(item.name||item.id)+' '+permissionLabel(flag)" :disabled="busy||entry.readonly" @change="syncSelected(item)"><span v-else class="muted">—</span></td></template>
        <template v-else><td><input class="input mapping-date" type="date" v-model="item.applyStartDate" :aria-label="(item.name||item.id)+' '+t('start')" :disabled="busy||entry.readonly||item.locked||!item.selected" :required="item.selected" min="0001-01-01" max="9999-12-31"></td><td class="date-separator">~</td><td><input class="input mapping-date" type="date" v-model="item.applyEndDate" :aria-label="(item.name||item.id)+' '+t('end')" :disabled="busy||entry.readonly||item.locked||!item.selected" :required="item.selected" min="0001-01-01" max="9999-12-31"></td></template>
       </tr>
      </tbody></table></div><p v-if="!visibleItems.length" class="empty-inline">{{t('empty')}}</p>
     </section>
    </template>
    <div v-if="error" role="alert" class="error-panel">{{error}}</div>
   </div>
   <footer class="dialog-footer"><span class="dialog-footer-note" v-if="entry.batch&&!discardStep">{{t('batch_hint')}}</span><div class="dialog-buttons"><template v-if="discardStep"><button type="button" class="button" @click="discardStep=false">{{t('stay')}}</button><button type="button" class="button is-danger" @click="finish({status:'cancelled',reason:'user'})">{{t('discard')}}</button></template><template v-else-if="entry.readonly"><button type="button" class="button" @click="cancel">{{t('close')}}</button></template><template v-else><button v-if="entry.kind!=='alert'" class="button" type="button" @click="cancel" :disabled="busy||entry.readonly">{{t('cancel')}}</button><button v-if="entry.alternative" class="button" type="button" :disabled="busy||entry.readonly" @click="alternative">{{entry.alternative.label}}</button><button type="submit" class="button" :class="entry.danger?'is-danger':'is-primary'" :disabled="busy||searching||entry.disabled">{{busy?t('saving'):entry.submitLabel||t(entry.kind==='alert'||entry.kind==='confirm'?'confirm':entry.batch?'apply':'save')}}</button></template></div></footer>
  </form>
 </dialog>
</template>
<script setup>
import {ref,computed,watch,nextTick,inject,onBeforeUnmount,onMounted} from 'vue';
import {filterMappingItems,mergeCandidates} from '@js/domain/authority.mjs';
import UserAvatar from './UserAvatar.vue';
const s=inject('kkdugi'),{state,t,clone}=s;const entry=computed(()=>state.dialogs[0]);const host=ref(null),form=ref({}),items=ref([]),query=ref(''),error=ref(''),busy=ref(false),searching=ref(false),discardStep=ref(false);const activeLanguage=ref(''),activeExtra=ref(1),imageFailed=ref(false);let initial='',previousFocus;
const profileUrl=computed(()=>{try{const url=new URL(form.value.image);return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return '';}});
const permissionFlags=computed(()=>entry.value?.permissionFlags||[...new Set(items.value.flatMap(i=>Object.keys(i.authorities||{})))]);
function permissionLabel(flag){const key={'10':'read','20':'write','30':'delete','40':'execute',READ:'read',WRITE:'write',EXECUTE:'execute'}[flag];return key?t(key):flag;}
function tabKey(event,values,current,kind){const key=event.key;if(!['ArrowLeft','ArrowRight','Home','End'].includes(key))return;event.preventDefault();let index=values.indexOf(current);index=key==='Home'?0:key==='End'?values.length-1:(index+(key==='ArrowRight'?1:-1)+values.length)%values.length;const value=values[index];if(kind==='language')activeLanguage.value=value;else activeExtra.value=value;nextTick(()=>host.value?.querySelector('#'+(kind==='language'?'lang':'extra')+'-tab-'+value)?.focus());}
const selectedItems=computed(()=>items.value.filter(i=>i.selected));const visibleItems=computed(()=>entry.value?.search?items.value:filterMappingItems(items.value,query.value,entry.value?.mapping==='menus'));
watch(()=>entry.value?.id,async id=>{if(!id)return;previousFocus=document.activeElement;form.value=clone(entry.value.initial||{});items.value=clone(entry.value.items||[]);query.value='';activeLanguage.value=entry.value.languages?.[0]?.code||'';activeExtra.value=1;imageFailed.value=false;error.value='';busy.value=false;discardStep.value=false;initial=snapshot();await nextTick();host.value?.showModal();host.value?.querySelector('#dialog-title')?.focus();document.body.classList.add('dialog-open');},{immediate:true});
function snapshot(){return JSON.stringify([form.value,entry.value?.mapping?items.value.filter(item=>item.selected):items.value]);}
function get(path){return path.split('.').reduce((v,k)=>v?.[k],form.value)??'';}function set(path,value){const bits=path.split('.');let cursor=form.value;for(const bit of bits.slice(0,-1))cursor=cursor[bit]??={};cursor[bits.at(-1)]=value;}
function finish(result){const current=entry.value;host.value?.close();document.body.classList.remove('dialog-open');s.settle(current,result);if(previousFocus?.isConnected)previousFocus.focus();}
function cancel(){if(busy.value)return;if(!['alert','confirm'].includes(entry.value.kind)&&snapshot()!==initial){discardStep.value=true;return;}finish({status:'cancelled',reason:'user'});}
function toggleItem(item){if(entry.value.mapping==='menus'&&!item.assignable)return;if(entry.value.mapping==='menus')for(const flag of Object.keys(item.authorities))item.authorities[flag]=item.selected;}
function syncSelected(item){item.selected=Object.values(item.authorities).some(Boolean);}
async function searchCandidates(){
 if(!entry.value?.search||searching.value||busy.value)return;
 const current=entry.value;searching.value=true;error.value='';
 try{const candidates=await current.search(query.value);if(entry.value?.id===current.id)items.value=mergeCandidates(items.value,candidates);}
 catch(e){if(entry.value?.id===current.id&&e.name!=='AbortError')error.value=s.errorText(e);}
 finally{if(entry.value?.id===current.id)searching.value=false;}
}
async function submit(){if(busy.value)return;if(entry.value.readonly){cancel();return;}busy.value=true;error.value='';try{if(selectedItems.value.some(i=>i.applyStartDate&&i.applyEndDate&&i.applyEndDate<i.applyStartDate))throw Error(t('invalid_date'));const value=entry.value.mapping?clone(items.value):clone(form.value);const validation=entry.value.validate?.(value);if(validation)throw Error(validation);const result=entry.value.onSubmit?await entry.value.onSubmit(value):value;finish({status:'submitted',value:result??value});}catch(e){error.value=e.status!==undefined?s.errorText(e):e.message;await nextTick();host.value?.querySelector('.error-panel')?.scrollIntoView({block:'nearest'});}finally{busy.value=false;}}
async function alternative(){busy.value=true;try{await entry.value.alternative.action?.();finish({status:'submitted',value:'alternative'});}catch(e){error.value=s.errorText(e);}finally{busy.value=false;}}
function viewportResize(){document.documentElement.style.setProperty('--dialog-height',(window.visualViewport?.height||window.innerHeight)+'px');}
onMounted(()=>{viewportResize();window.visualViewport?.addEventListener('resize',viewportResize);});
onBeforeUnmount(()=>{window.visualViewport?.removeEventListener('resize',viewportResize);document.body.classList.remove('dialog-open');for(const d of [...state.dialogs])s.settle(d,{status:'cancelled',reason:'owner-disposed'});});
</script>
