// Component smoke test with an in-memory Vue renderer. This is not browser QA.
import vm from 'node:vm';import fs from 'node:fs/promises';import path from 'node:path';
import * as domain from '../src/main/resources/static/admin/domain.mjs';
import {createDemoApi} from '../src/main/resources/static/admin/demo.mjs';
import {translate} from '../src/main/resources/static/admin/i18n.mjs';
const root=path.resolve(import.meta.dirname,'../src/main/resources/static');
const noop=()=>{};const errors=[];
const c=vm.createContext({console,TextEncoder,TextDecoder,URL,URLSearchParams,setTimeout,clearTimeout,atob,btoa,history:{replaceState:noop},location:{hash:'#admcode'},crypto:globalThis.crypto});c.window=c;c.self=c;c.globalThis=c;c.addEventListener=noop;c.removeEventListener=noop;c.innerHeight=900;
vm.runInContext(await fs.readFile(path.join(root,'vendor/vue.global.prod.js'),'utf8'),c);vm.runInContext(await fs.readFile(path.join(root,'vendor/vue3-sfc-loader.js'),'utf8'),c);
c.document={documentElement:{style:{setProperty:noop}},body:{classList:{add:noop,remove:noop}},querySelector:()=>null,activeElement:null};
let gridRows=[];c.agGrid={themeQuartz:{withParams:()=>({})},createGrid:(el,options)=>{gridRows=options.rowData;return {setGridOption:(key,val)=>{if(key==='rowData')gridRows=val;},destroy:noop,stopEditing:noop,deselectAll:noop,getSelectedRows:()=>[]};}};
const component=await c['vue3-sfc-loader'].loadModule('/admin/App.vue',{moduleCache:{vue:c.Vue},getFile:url=>fs.readFile(path.join(root,url),'utf8'),addStyle:noop});
function node(type,text=''){return {type,text,children:[],props:{},parent:null,style:{},options:[],addEventListener:noop,removeEventListener:noop,setAttribute:noop,removeAttribute:noop,showModal:noop,close:noop,querySelector:()=>({focus:noop,scrollIntoView:noop})};}
const renderer=c.Vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('#text',text),createComment:text=>node('#comment',text),setText:(n,t)=>n.text=t,setElementText:(n,t)=>n.text=t,parentNode:n=>n.parent,nextSibling:n=>n.parent?.children[n.parent.children.indexOf(n)+1]||null,patchProp:(n,key,old,val)=>n.props[key]=val,insert:(n,parent,anchor)=>{if(n.parent)n.parent.children=n.parent.children.filter(x=>x!==n);const i=anchor?parent.children.indexOf(anchor):-1;if(i<0)parent.children.push(n);else parent.children.splice(i,0,n);n.parent=parent;},remove:n=>{if(n.parent)n.parent.children=n.parent.children.filter(x=>x!==n);},insertStaticContent:()=>{throw Error('Unexpected static DOM dependency');}});
for(const screen of Object.keys(domain.screenDefs)){c.location.hash='#'+screen;const state=c.Vue.reactive({locale:'ko_KR',dialogs:[],notice:''});const service={...domain,config:{mode:'preview'},state,t:k=>translate(state.locale,k),languages:[{code:'ko_KR',label:'한국어'},{code:'en_US',label:'English'}],statuses:['ACTIVE','INACTIVE','LOCKED'],api:createDemoApi(),notify:noop,errorText:e=>e.message,dialog:{},settle:(entry,result)=>{state.dialogs.shift();entry.resolve(result);}};const app=renderer.createApp(component);app.config.errorHandler=e=>errors.push(e);app.provide('kkdugi',service);const host=node('root');app.mount(host);await new Promise(r=>setTimeout(r,140));await c.Vue.nextTick();if(!gridRows.length)throw Error('No loaded rows on '+screen);state.dialogs.push({id:1,kind:'form',title:'Test',fields:[{path:'name',label:'Name'}],initial:{name:'Test'},resolve:noop});await c.Vue.nextTick();await c.Vue.nextTick();app.unmount();console.log(`Rendered ${screen} and dialog with ${gridRows.length} rows`);}
if(errors.length){console.error([...new Set(errors.map(e=>e.message))]);process.exitCode=1;}
