-- =========================================================================
-- KKDUGI Schema (PostgreSQL)
-- =========================================================================

-- -------------------------------------------------------------------------
-- KKDUGI_AUTH_BASE : 권한
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_AUTH_BASE (
    AUTH_ID      VARCHAR(20)   NOT NULL,
    AUTH_ROLE_CD VARCHAR(20)   NOT NULL,
    AUTH_TP_CD   VARCHAR(20)   NOT NULL,
    AUTH_NM      VARCHAR(200)  NOT NULL,
    AUTH_DC      VARCHAR(4000),
    USE_YN       CHAR(1)       NOT NULL,
    REG_DTM      TIMESTAMP     NOT NULL,
    REG_ID       VARCHAR(20)   NOT NULL,
    UPD_DTM      TIMESTAMP,
    UPD_ID       VARCHAR(20),
    CONSTRAINT KKDUGI_AUTH_BASE_PK PRIMARY KEY (AUTH_ID)
);

COMMENT ON COLUMN KKDUGI_AUTH_BASE.AUTH_ID      IS '권한 ID';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.AUTH_ROLE_CD IS '권한 ROLE 코드 (공통코드 /SYS/AUTH/ROLE)';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.AUTH_TP_CD   IS '권한 유형 코드 (공통코드 /SYS/AUTH/TYPE)';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.AUTH_NM      IS '권한 이름';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.AUTH_DC      IS '권한 설명';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.USE_YN       IS '사용 여부';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.REG_DTM      IS '등록일시';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.REG_ID       IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.UPD_DTM      IS '수정일시';
COMMENT ON COLUMN KKDUGI_AUTH_BASE.UPD_ID       IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_AUTH_MENU : 권한 메뉴
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_AUTH_MENU (
    AUTH_ID  VARCHAR(20) NOT NULL,
    MENU_ID  VARCHAR(20) NOT NULL,
    AUTH_VAL INTEGER     NOT NULL,
    REG_DTM  TIMESTAMP   NOT NULL,
    REG_ID   VARCHAR(20) NOT NULL,
    UPD_DTM  TIMESTAMP,
    UPD_ID   VARCHAR(20),
    CONSTRAINT KKDUGI_AUTH_MENU_PK PRIMARY KEY (AUTH_ID, MENU_ID)
);

COMMENT ON TABLE KKDUGI_AUTH_MENU IS '권한 메뉴';

COMMENT ON COLUMN KKDUGI_AUTH_MENU.AUTH_ID  IS '권한 ID';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.MENU_ID  IS '메뉴 ID';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.AUTH_VAL IS '권한 값 (공통코드 /SYS/AUTH/MENU)';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.REG_DTM  IS '등록일시';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.REG_ID   IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.UPD_DTM  IS '수정일시';
COMMENT ON COLUMN KKDUGI_AUTH_MENU.UPD_ID   IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_CODE_BASE : 코드
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_CODE_BASE (
    CODE_ID        VARCHAR(20)   NOT NULL,
    CODE_PARENT_ID VARCHAR(20),
    CODE_VAL       VARCHAR(20)   NOT NULL,
    ETC_VAL1       VARCHAR(4000),
    ETC_VAL2       VARCHAR(4000),
    ETC_VAL3       VARCHAR(4000),
    ETC_VAL4       VARCHAR(4000),
    ETC_VAL5       VARCHAR(4000),
    CODE_LVL       INTEGER,
    CODE_PATH      VARCHAR(2000),
    SORT_SEQ       INTEGER,
    USE_YN         CHAR(1)       NOT NULL,
    REG_DTM        TIMESTAMP     NOT NULL,
    REG_ID         VARCHAR(20)   NOT NULL,
    UPD_DTM        TIMESTAMP,
    UPD_ID         VARCHAR(20),
    CONSTRAINT KKDUGI_CODE_PK PRIMARY KEY (CODE_ID),
    CONSTRAINT KKDUGI_CODE_BASE_UDX_PARENT_VAL UNIQUE (CODE_PARENT_ID, CODE_VAL)
);

COMMENT ON TABLE KKDUGI_CODE_BASE IS '코드';

COMMENT ON COLUMN KKDUGI_CODE_BASE.CODE_ID        IS '코드 ID';
COMMENT ON COLUMN KKDUGI_CODE_BASE.CODE_PARENT_ID IS '상위 코드 ID (ROOT인 경우 NULL - KKDUGI_MENU_BASE/KKDUGI_ORGA_BASE의 루트 표현과 통일)';
COMMENT ON COLUMN KKDUGI_CODE_BASE.CODE_VAL       IS '코드 값';
COMMENT ON COLUMN KKDUGI_CODE_BASE.ETC_VAL1       IS '추가 값 1';
COMMENT ON COLUMN KKDUGI_CODE_BASE.ETC_VAL2       IS '추가 값 2';
COMMENT ON COLUMN KKDUGI_CODE_BASE.ETC_VAL3       IS '추가 값 3';
COMMENT ON COLUMN KKDUGI_CODE_BASE.ETC_VAL4       IS '추가 값 4';
COMMENT ON COLUMN KKDUGI_CODE_BASE.ETC_VAL5       IS '추가 값 5';
COMMENT ON COLUMN KKDUGI_CODE_BASE.CODE_LVL       IS '코드 Hierarchy level (시스템 관리)';
COMMENT ON COLUMN KKDUGI_CODE_BASE.CODE_PATH      IS '코드 Hierarchy path (시스템 관리) - CODE_VAL을 ''/''로 이어붙인 값 (예: /SYS/USER/STAT). 공통코드 조회는 CODE_ID가 아닌 이 CODE_PATH로 수행한다';
COMMENT ON COLUMN KKDUGI_CODE_BASE.SORT_SEQ       IS '정렬 순번';
COMMENT ON COLUMN KKDUGI_CODE_BASE.USE_YN         IS '사용 여부';
COMMENT ON COLUMN KKDUGI_CODE_BASE.REG_DTM        IS '등록일시';
COMMENT ON COLUMN KKDUGI_CODE_BASE.REG_ID         IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_CODE_BASE.UPD_DTM        IS '수정일시';
COMMENT ON COLUMN KKDUGI_CODE_BASE.UPD_ID         IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_CODE_LANG : 코드 언어
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_CODE_LANG (
    CODE_ID VARCHAR(20)  NOT NULL,
    LANG_CD VARCHAR(20)  NOT NULL,
    CODE_NM VARCHAR(200) NOT NULL,
    CODE_DC VARCHAR(4000),
    REG_DTM TIMESTAMP    NOT NULL,
    REG_ID  VARCHAR(20)  NOT NULL,
    UPD_DTM TIMESTAMP,
    UPD_ID  VARCHAR(20),
    CONSTRAINT KKDUGI_CODE_LANG_PK PRIMARY KEY (CODE_ID, LANG_CD)
);

COMMENT ON TABLE KKDUGI_CODE_LANG IS '코드 언어';

COMMENT ON COLUMN KKDUGI_CODE_LANG.CODE_ID IS '코드 ID';
COMMENT ON COLUMN KKDUGI_CODE_LANG.LANG_CD IS '언어 코드 (공통코드 /SYS/LANG)';
COMMENT ON COLUMN KKDUGI_CODE_LANG.CODE_NM IS '코드 이름';
COMMENT ON COLUMN KKDUGI_CODE_LANG.CODE_DC IS '코드 설명';
COMMENT ON COLUMN KKDUGI_CODE_LANG.REG_DTM IS '등록일시';
COMMENT ON COLUMN KKDUGI_CODE_LANG.REG_ID  IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_CODE_LANG.UPD_DTM IS '수정일시';
COMMENT ON COLUMN KKDUGI_CODE_LANG.UPD_ID  IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_I18N_MSG : 다국어 언어 코드
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_I18N_MSG (
    MSG_CD  VARCHAR(20) NOT NULL,
    LANG_CD VARCHAR(20) NOT NULL,
    MSG_VAL VARCHAR(4000),
    REG_DTM TIMESTAMP   NOT NULL,
    REG_ID  VARCHAR(20) NOT NULL,
    UPD_DTM TIMESTAMP,
    UPD_ID  VARCHAR(20),
    CONSTRAINT KKDUGI_I18N_MSG_PK PRIMARY KEY (MSG_CD, LANG_CD)
);

COMMENT ON TABLE KKDUGI_I18N_MSG IS '다국어 언어 코드';

COMMENT ON COLUMN KKDUGI_I18N_MSG.MSG_CD  IS '메시지 코드';
COMMENT ON COLUMN KKDUGI_I18N_MSG.LANG_CD IS '언어 코드 (공통코드 /SYS/LANG)';
COMMENT ON COLUMN KKDUGI_I18N_MSG.MSG_VAL IS '메시지';
COMMENT ON COLUMN KKDUGI_I18N_MSG.REG_DTM IS '등록일시';
COMMENT ON COLUMN KKDUGI_I18N_MSG.REG_ID  IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_I18N_MSG.UPD_DTM IS '수정일시';
COMMENT ON COLUMN KKDUGI_I18N_MSG.UPD_ID  IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_MENU_BASE : 메뉴
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_MENU_BASE (
    MENU_ID        VARCHAR(20)  NOT NULL,
    MENU_PARENT_ID VARCHAR(20),
    MENU_ICO       VARCHAR(200),
    MENU_PGM       VARCHAR(20),
    MENU_LVL       INTEGER,
    MENU_PATH      VARCHAR(2000),
    SORT_SEQ       INTEGER,
    USE_YN         CHAR(1)      NOT NULL,
    CLOSE_YN       CHAR(1)      NOT NULL,
    REG_DTM        TIMESTAMP    NOT NULL,
    REG_ID         VARCHAR(20)  NOT NULL,
    UPD_DTM        TIMESTAMP,
    UPD_ID         VARCHAR(20),
    CONSTRAINT KKDUGI_MENU_BASE_PK PRIMARY KEY (MENU_ID)
);

COMMENT ON TABLE KKDUGI_MENU_BASE IS '메뉴';

COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_ID        IS '메뉴 ID';
COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_PARENT_ID IS '상위 메뉴 ID (Root는 NULL)';
COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_ICO       IS '메뉴 아이콘 (반드시 full class name)';
COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_PGM       IS '메뉴 프로그램 ID';
COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_LVL       IS '메뉴 Hierarchy level (시스템 관리)';
COMMENT ON COLUMN KKDUGI_MENU_BASE.MENU_PATH      IS '메뉴 Hierarchy path (시스템 관리)';
COMMENT ON COLUMN KKDUGI_MENU_BASE.SORT_SEQ       IS '정렬 순번';
COMMENT ON COLUMN KKDUGI_MENU_BASE.USE_YN         IS '사용 여부';
COMMENT ON COLUMN KKDUGI_MENU_BASE.CLOSE_YN       IS '탭 UI인 경우 닫을 수 있는지 여부';
COMMENT ON COLUMN KKDUGI_MENU_BASE.REG_DTM        IS '등록일시';
COMMENT ON COLUMN KKDUGI_MENU_BASE.REG_ID         IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_MENU_BASE.UPD_DTM        IS '수정일시';
COMMENT ON COLUMN KKDUGI_MENU_BASE.UPD_ID         IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_MENU_LANG : 메뉴 언어 페이지
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_MENU_LANG (
    MENU_ID VARCHAR(20)  NOT NULL,
    LANG_CD VARCHAR(20)  NOT NULL,
    MENU_NM VARCHAR(200) NOT NULL,
    MENU_DC VARCHAR(4000),
    REG_DTM TIMESTAMP    NOT NULL,
    REG_ID  VARCHAR(20)  NOT NULL,
    UPD_DTM TIMESTAMP,
    UPD_ID  VARCHAR(20),
    CONSTRAINT KKDUGI_MENU_LANG_PK PRIMARY KEY (MENU_ID, LANG_CD)
);

COMMENT ON TABLE KKDUGI_MENU_LANG IS '메뉴 언어 페이지';

COMMENT ON COLUMN KKDUGI_MENU_LANG.MENU_ID IS '메뉴 ID';
COMMENT ON COLUMN KKDUGI_MENU_LANG.LANG_CD IS '언어 코드 (공통코드 /SYS/LANG)';
COMMENT ON COLUMN KKDUGI_MENU_LANG.MENU_NM IS '메뉴 이름';
COMMENT ON COLUMN KKDUGI_MENU_LANG.MENU_DC IS '메뉴 설명';
COMMENT ON COLUMN KKDUGI_MENU_LANG.REG_DTM IS '등록일시';
COMMENT ON COLUMN KKDUGI_MENU_LANG.REG_ID  IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_MENU_LANG.UPD_DTM IS '수정일시';
COMMENT ON COLUMN KKDUGI_MENU_LANG.UPD_ID  IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_ORGA_AUTH : 조직 권한
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_ORGA_AUTH (
    ORGA_ID    VARCHAR(20) NOT NULL,
    AUTH_ID    VARCHAR(20) NOT NULL,
    APL_ST_DTM DATE        NOT NULL,
    APL_ED_DTM DATE        NOT NULL,
    REG_DTM    TIMESTAMP   NOT NULL,
    REG_ID     VARCHAR(20) NOT NULL,
    UPD_DTM    TIMESTAMP,
    UPD_ID     VARCHAR(20),
    CONSTRAINT KKDUGI_ORGA_AUTH_PK PRIMARY KEY (ORGA_ID, AUTH_ID)
);

COMMENT ON TABLE KKDUGI_ORGA_AUTH IS '조직 권한';

COMMENT ON COLUMN KKDUGI_ORGA_AUTH.ORGA_ID    IS '조직 ID';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.AUTH_ID    IS '권한 ID';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.APL_ST_DTM IS '적용 시작 일시';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.APL_ED_DTM IS '적용 종료 일시';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.REG_DTM    IS '등록일시';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.REG_ID     IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.UPD_DTM    IS '수정일시';
COMMENT ON COLUMN KKDUGI_ORGA_AUTH.UPD_ID     IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_ORGA_BASE : 조직
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_ORGA_BASE (
    ORGA_ID        VARCHAR(20)  NOT NULL,
    ORGA_PARENT_ID VARCHAR(20),
    ORGA_CD        VARCHAR(20)  NOT NULL,
    ORGA_TP_CD     VARCHAR(20)  NOT NULL,
    ORGA_LVL       INTEGER,
    ORGA_PATH      VARCHAR(2000),
    SORT_SEQ       INTEGER,
    USE_YN         CHAR(1)      NOT NULL,
    REG_DTM        TIMESTAMP    NOT NULL,
    REG_ID         VARCHAR(20)  NOT NULL,
    UPD_DTM        TIMESTAMP,
    UPD_ID         VARCHAR(20),
    CONSTRAINT KKDUGI_ORGA_BASE_PK PRIMARY KEY (ORGA_ID)
);

COMMENT ON TABLE KKDUGI_ORGA_BASE IS '조직';

COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_ID        IS '조직 ID';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_PARENT_ID IS '상위 조직 ID';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_CD        IS '조직 코드';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_TP_CD     IS '조직 유형 코드 (/SYS/ORGA/TYPE)';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_LVL       IS '조직 Hierarchy level (시스템 관리)';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.ORGA_PATH      IS '조직 Hierarchy path (시스템 관리)';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.SORT_SEQ       IS '정렬 순번';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.USE_YN         IS '사용 여부';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.REG_DTM        IS '등록일시';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.REG_ID         IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.UPD_DTM        IS '수정일시';
COMMENT ON COLUMN KKDUGI_ORGA_BASE.UPD_ID         IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_ORGA_LANG : 조직 언어 페이지
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_ORGA_LANG (
    ORGA_ID VARCHAR(20)  NOT NULL,
    LANG_CD VARCHAR(20)  NOT NULL,
    ORGA_NM VARCHAR(200) NOT NULL,
    ORGA_DC VARCHAR(4000),
    REG_DTM TIMESTAMP    NOT NULL,
    REG_ID  VARCHAR(20)  NOT NULL,
    UPD_DTM TIMESTAMP,
    UPD_ID  VARCHAR(20),
    CONSTRAINT KKDUGI_ORGA_LANG_PK PRIMARY KEY (ORGA_ID, LANG_CD)
);

COMMENT ON TABLE KKDUGI_ORGA_LANG IS '조직 언어 페이지';

COMMENT ON COLUMN KKDUGI_ORGA_LANG.ORGA_ID IS '조직 ID';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.LANG_CD IS '언어 코드 (공통코드 /SYS/LANG)';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.ORGA_NM IS '조직 이름';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.ORGA_DC IS '조직 설명';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.REG_DTM IS '등록일시';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.REG_ID  IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.UPD_DTM IS '수정일시';
COMMENT ON COLUMN KKDUGI_ORGA_LANG.UPD_ID  IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_ORGA_USER : 조직 사용자
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_ORGA_USER (
    ORGA_ID      VARCHAR(20) NOT NULL,
    USER_ID      VARCHAR(20) NOT NULL,
    USER_POSA_CD VARCHAR(20),
    USER_JOBA_CD VARCHAR(20),
    MNGR_YN      CHAR(1)     NOT NULL,
    REG_DTM      TIMESTAMP   NOT NULL,
    REG_ID       VARCHAR(20) NOT NULL,
    UPD_DTM      TIMESTAMP,
    UPD_ID       VARCHAR(20),
    CONSTRAINT KKDUGI_ORGA_USER_PK PRIMARY KEY (ORGA_ID, USER_ID)
);

COMMENT ON TABLE KKDUGI_ORGA_USER IS '조직 사용자';

COMMENT ON COLUMN KKDUGI_ORGA_USER.ORGA_ID      IS '조직 ID';
COMMENT ON COLUMN KKDUGI_ORGA_USER.USER_ID      IS '사용자 ID (시스템 생성)';
COMMENT ON COLUMN KKDUGI_ORGA_USER.USER_POSA_CD IS '직책코드 (공통코드 /SYS/ORGA/POSA)';
COMMENT ON COLUMN KKDUGI_ORGA_USER.USER_JOBA_CD IS '직급 코드 (공통코드 /SYS/ORGA/JOBA)';
COMMENT ON COLUMN KKDUGI_ORGA_USER.MNGR_YN      IS '조직 관리자 여부';
COMMENT ON COLUMN KKDUGI_ORGA_USER.REG_DTM      IS '등록일시';
COMMENT ON COLUMN KKDUGI_ORGA_USER.REG_ID       IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_ORGA_USER.UPD_DTM      IS '수정일시';
COMMENT ON COLUMN KKDUGI_ORGA_USER.UPD_ID       IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_SERIAL_BASE : 일련번호
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_SERIAL_BASE (
    SERIAL_ID VARCHAR(20) NOT NULL,
    SEQ_BASE  VARCHAR(20) NOT NULL,
    SEQ_VAL   INTEGER     NOT NULL,
    UPD_DTM   TIMESTAMP   NOT NULL,
    CONSTRAINT KKDUGI_SERIAL_BASE_PK PRIMARY KEY (SERIAL_ID)
);

COMMENT ON TABLE KKDUGI_SERIAL_BASE IS '일련번호';

COMMENT ON COLUMN KKDUGI_SERIAL_BASE.SERIAL_ID IS '일련번호 ID';
COMMENT ON COLUMN KKDUGI_SERIAL_BASE.SEQ_BASE  IS '일련번호 채번 기준';
COMMENT ON COLUMN KKDUGI_SERIAL_BASE.SEQ_VAL   IS '일련번호 값';
COMMENT ON COLUMN KKDUGI_SERIAL_BASE.UPD_DTM   IS '수정일시';

-- KKDUGI_FN_NEXT_SERIAL(p_SERIAL_ID, p_SEQ_BASE, p_INCREMENT)
--   같은 SEQ_BASE(채번 기준)로 다시 호출되면 기존 SEQ_VAL에 p_INCREMENT를 더하고,
--   SEQ_BASE가 바뀌면(최초 채번 포함) SEQ_VAL은 p_INCREMENT부터 새로 시작한다.
--   INSERT ... ON CONFLICT DO UPDATE 한 문장으로 조회와 갱신을 원자적으로 처리하므로,
--   여러 인스턴스에서 동시에 같은 SERIAL_ID를 호출해도 행 잠금에 의해 직렬화되어
--   값 유실이나 중복 채번 없이 안전하다.
CREATE OR REPLACE FUNCTION KKDUGI_FN_NEXT_SERIAL(
    p_SERIAL_ID VARCHAR(20),
    p_SEQ_BASE  VARCHAR(20),
    p_INCREMENT INTEGER DEFAULT 1
) RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_SEQ_VAL INTEGER;
BEGIN
    IF p_INCREMENT IS NULL OR p_INCREMENT < 1 THEN
        RAISE EXCEPTION 'p_INCREMENT must be a positive integer';
    END IF;

    INSERT INTO KKDUGI_SERIAL_BASE (SERIAL_ID, SEQ_BASE, SEQ_VAL, UPD_DTM)
    VALUES (p_SERIAL_ID, p_SEQ_BASE, p_INCREMENT, clock_timestamp())
    ON CONFLICT (SERIAL_ID) DO UPDATE
        SET SEQ_VAL  = CASE WHEN KKDUGI_SERIAL_BASE.SEQ_BASE = p_SEQ_BASE
                             THEN KKDUGI_SERIAL_BASE.SEQ_VAL + p_INCREMENT
                             ELSE p_INCREMENT
                        END,
            SEQ_BASE = p_SEQ_BASE,
            UPD_DTM  = clock_timestamp()
    RETURNING SEQ_VAL INTO v_SEQ_VAL;

    RETURN v_SEQ_VAL;
END;
$$;

COMMENT ON FUNCTION KKDUGI_FN_NEXT_SERIAL(VARCHAR, VARCHAR, INTEGER) IS
    '일련번호 채번: SEQ_BASE(키)가 같으면 SEQ_VAL + p_INCREMENT, 다르면 p_INCREMENT부터 새로 시작. INSERT ... ON CONFLICT 행 잠금으로 다중 인스턴스 동시 호출에도 안전하게 채번된다.';


-- -------------------------------------------------------------------------
-- KKDUGI_SESSION : 세션
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_SESSION (
    SESS_ID  VARCHAR(20) NOT NULL,
    USER_ID  VARCHAR(20) NOT NULL,
    USER_DTL BYTEA,
    REG_DTM  TIMESTAMP   NOT NULL,
    EXP_DTM  TIMESTAMP   NOT NULL,
    UPD_DTM  TIMESTAMP   NOT NULL,
    CONSTRAINT KKDUGI_SESSION_PK PRIMARY KEY (SESS_ID)
);

COMMENT ON TABLE KKDUGI_SESSION IS '세션';

COMMENT ON COLUMN KKDUGI_SESSION.SESS_ID  IS '세션 ID';
COMMENT ON COLUMN KKDUGI_SESSION.USER_ID  IS '사용자 ID (시스템 생성)';
COMMENT ON COLUMN KKDUGI_SESSION.USER_DTL IS '사용자 데이터 (JSON 직렬화)';
COMMENT ON COLUMN KKDUGI_SESSION.REG_DTM  IS '등록일시';
COMMENT ON COLUMN KKDUGI_SESSION.EXP_DTM  IS '만료일시';
COMMENT ON COLUMN KKDUGI_SESSION.UPD_DTM  IS '수정일시';


-- -------------------------------------------------------------------------
-- KKDUGI_USER_AUTH : 사용자 권한
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_USER_AUTH (
    USER_ID    VARCHAR(20) NOT NULL,
    AUTH_ID    VARCHAR(20) NOT NULL,
    APL_ST_DTM DATE        NOT NULL,
    APL_ED_DTM DATE        NOT NULL,
    REG_DTM    TIMESTAMP   NOT NULL,
    REG_ID     VARCHAR(20) NOT NULL,
    UPD_DTM    TIMESTAMP,
    UPD_ID     VARCHAR(20),
    CONSTRAINT KKDUGI_USER_AUTH_PK PRIMARY KEY (USER_ID, AUTH_ID)
);

COMMENT ON TABLE KKDUGI_USER_AUTH IS '사용자 권한';

COMMENT ON COLUMN KKDUGI_USER_AUTH.USER_ID    IS '사용자 ID (시스템 생성)';
COMMENT ON COLUMN KKDUGI_USER_AUTH.AUTH_ID    IS '권한 ID';
COMMENT ON COLUMN KKDUGI_USER_AUTH.APL_ST_DTM IS '적용 시작 일시';
COMMENT ON COLUMN KKDUGI_USER_AUTH.APL_ED_DTM IS '적용 종료 일시';
COMMENT ON COLUMN KKDUGI_USER_AUTH.REG_DTM    IS '등록일시';
COMMENT ON COLUMN KKDUGI_USER_AUTH.REG_ID     IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_USER_AUTH.UPD_DTM    IS '수정일시';
COMMENT ON COLUMN KKDUGI_USER_AUTH.UPD_ID     IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_USER_BASE : 사용자
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_USER_BASE (
    USER_ID          VARCHAR(20)   NOT NULL,
    USER_LOGIN_ID    VARCHAR(200)  NOT NULL,
    USER_PWD         VARCHAR(2048),
    USER_NM          VARCHAR(200)  NOT NULL,
    USER_DC          VARCHAR(4000),
    USER_EMAIL       VARCHAR(200)  NOT NULL,
    USER_IMG_SRC     VARCHAR(2000),
    USER_CI          VARCHAR(2048),
    USER_DI          VARCHAR(2048),
    LAST_LOGIN_DTM   TIMESTAMP,
    LAST_CHG_PWD_DTM TIMESTAMP,
    PWD_STAT_CD      VARCHAR(20),
    PWD_EXPR_DTM     TIMESTAMP,
    USER_STAT_CD     VARCHAR(20)   NOT NULL,
    USER_SET_DATA    BYTEA,
    REG_DTM          TIMESTAMP     NOT NULL,
    REG_ID           VARCHAR(20)   NOT NULL,
    UPD_DTM          TIMESTAMP,
    UPD_ID           VARCHAR(20),
    CONSTRAINT KKDUGI_USER_BASE_PK PRIMARY KEY (USER_ID),
    CONSTRAINT KKDUGI_USER_BASE_UDX_EMAIL UNIQUE (USER_EMAIL)
);

COMMENT ON TABLE KKDUGI_USER_BASE IS '사용자';

COMMENT ON COLUMN KKDUGI_USER_BASE.USER_ID          IS '사용자 ID (시스템 생성)';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_LOGIN_ID    IS '사용자 로그인 ID';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_PWD         IS '사용자 비밀번호';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_NM          IS '사용자 이름';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_DC          IS '사용자 설명 (프로필)';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_EMAIL       IS '사용자 이메일주소';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_IMG_SRC     IS '사용자 프로필 이미지';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_CI          IS '사용자 CI';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_DI          IS '사용자 DI';
COMMENT ON COLUMN KKDUGI_USER_BASE.LAST_LOGIN_DTM   IS '마지막 로그인 일시';
COMMENT ON COLUMN KKDUGI_USER_BASE.LAST_CHG_PWD_DTM IS '마지막 비밀번호 변경 일시';
COMMENT ON COLUMN KKDUGI_USER_BASE.PWD_STAT_CD      IS '비밀번호 상태 코드 (공통코드 /SYS/USER/PWD_STAT)';
COMMENT ON COLUMN KKDUGI_USER_BASE.PWD_EXPR_DTM     IS '비밀번호 만료 일시';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_STAT_CD     IS '사용자 상태 코드 (공통코드 /SYS/USER/STAT): 10 대기(로그인 불가), 20 정상(로그인 가능), 30 탈퇴(로그인 불가), 40 제한(로그인 불가)';
COMMENT ON COLUMN KKDUGI_USER_BASE.USER_SET_DATA    IS '사용자 설정 데이터 (JSON 직렬화)';
COMMENT ON COLUMN KKDUGI_USER_BASE.REG_DTM          IS '등록일시';
COMMENT ON COLUMN KKDUGI_USER_BASE.REG_ID           IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_USER_BASE.UPD_DTM          IS '수정일시';
COMMENT ON COLUMN KKDUGI_USER_BASE.UPD_ID           IS '수정자 ID';


-- -------------------------------------------------------------------------
-- KKDUGI_WIDGET_AUDIT : 위젯 변경·실행 감사
-- 카탈로그 삭제 후에도 보존하므로 위젯/버전 FK 없음.
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_WIDGET_AUDIT (
    AUDIT_ID    BIGINT GENERATED ALWAYS AS IDENTITY,
    WIDG_ID     VARCHAR(20),
    REV_ID      VARCHAR(36),
    DATASET_KEY VARCHAR(50),
    ACTION_CD   VARCHAR(30) NOT NULL,
    RESULT_CD   VARCHAR(20) NOT NULL,
    ELAPSED_MS  BIGINT,
    ROW_CNT     INTEGER,
    REG_DTM     TIMESTAMP   NOT NULL DEFAULT now(),
    REG_ID      VARCHAR(20) NOT NULL,
    CONSTRAINT KKDUGI_WIDGET_AUDIT_PK PRIMARY KEY (AUDIT_ID)
);

COMMENT ON TABLE KKDUGI_WIDGET_AUDIT IS '위젯 변경·실행 감사. 카탈로그 삭제 후 보존하므로 위젯/버전 FK 없음. REG_DTM 조회 인덱스.';

COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.AUDIT_ID    IS '감사 이력 ID';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.WIDG_ID     IS '위젯 ID';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.REV_ID      IS '버전 ID';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.DATASET_KEY IS '데이터셋 키';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.ACTION_CD   IS '작업 코드';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.RESULT_CD   IS '실행 결과 코드';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.ELAPSED_MS  IS '소요시간(ms)';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.ROW_CNT     IS '반환 행 수';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.REG_DTM     IS '등록일시';
COMMENT ON COLUMN KKDUGI_WIDGET_AUDIT.REG_ID      IS '등록자 ID';

CREATE INDEX KKDUGI_WIDGET_AUDIT_IDX_REG_DTM ON KKDUGI_WIDGET_AUDIT (REG_DTM);


-- -------------------------------------------------------------------------
-- KKDUGI_WIDGET_DATASET : 버전별 SQL 데이터셋
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_WIDGET_DATASET (
    REV_ID      VARCHAR(36) NOT NULL,
    DATASET_KEY VARCHAR(50) NOT NULL,
    SQL_SRC     TEXT        NOT NULL,
    PARAM_DEF   JSONB       NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT KKDUGI_WIDGET_DATASET_PK PRIMARY KEY (REV_ID, DATASET_KEY)
);

COMMENT ON TABLE KKDUGI_WIDGET_DATASET IS '버전별 SQL 데이터셋. PARAM_DEF는 JSONB.';

COMMENT ON COLUMN KKDUGI_WIDGET_DATASET.REV_ID      IS '버전 ID';
COMMENT ON COLUMN KKDUGI_WIDGET_DATASET.DATASET_KEY IS '데이터셋 키';
COMMENT ON COLUMN KKDUGI_WIDGET_DATASET.SQL_SRC     IS '조회 SQL 소스';
COMMENT ON COLUMN KKDUGI_WIDGET_DATASET.PARAM_DEF   IS '파라미터 타입 정의';


-- -------------------------------------------------------------------------
-- KKDUGI_WIDGET_QUERY_TABLE : SQL 조회 허용 테이블 목록
-- -------------------------------------------------------------------------
CREATE TABLE KKDUGI_WIDGET_QUERY_TABLE (
    SCHEMA_NM VARCHAR(63)  NOT NULL,
    TABLE_NM  VARCHAR(63)  NOT NULL,
    TABLE_DC  VARCHAR(500),
    USE_YN    CHAR(1)      NOT NULL DEFAULT 'N' CHECK (USE_YN IN ('Y', 'N')),
    REG_DTM   TIMESTAMP    NOT NULL DEFAULT now(),
    REG_ID    VARCHAR(20)  NOT NULL,
    UPD_DTM   TIMESTAMP,
    UPD_ID    VARCHAR(20),
    CONSTRAINT KKDUGI_WIDGET_QUERY_TABLE_PK PRIMARY KEY (SCHEMA_NM, TABLE_NM)
);

COMMENT ON TABLE KKDUGI_WIDGET_QUERY_TABLE IS 'SQL 조회 허용 테이블 목록. USE_YN은 Y/N, 기본 N. 실제 SELECT 권한도 확인.';

COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.SCHEMA_NM IS '허용 스키마명';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.TABLE_NM  IS '허용 테이블명';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.TABLE_DC  IS '허용 테이블 설명';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.USE_YN    IS '조회 허용 여부';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.REG_DTM   IS '등록일시';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.REG_ID    IS '등록자 ID';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.UPD_DTM   IS '수정일시';
COMMENT ON COLUMN KKDUGI_WIDGET_QUERY_TABLE.UPD_ID    IS '수정자 ID';
